version: '3.8'

# All storage backend services for development
# Start with: docker-compose -f docker-compose.backends.yml up -d
# Stop with: docker-compose -f docker-compose.backends.yml down

services:
  # PostgreSQL - SQL relational database
  postgres:
    image: postgres:15
    container_name: godocgo-postgres
    environment:
      POSTGRES_DB: godocgo_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB - NoSQL document database
  mongodb:
    image: mongo:6
    container_name: godocgo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Elasticsearch - Full-text search engine
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: godocgo-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Neo4j - Graph database
  neo4j:
    image: neo4j:5
    container_name: godocgo-neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_memory_pagecache_size: 512M
      NEO4J_dbms_memory_heap_max__size: 512M
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Apache Solr - Enterprise search platform
  solr:
    image: solr:9
    container_name: godocgo-solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - godocgo
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8983/solr/admin/cores?action=STATUS || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
  elastic_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  solr_data:
    driver: local

networks:
  default:
    name: godocgo-network
    driver: bridge