"""
Test to compare embeddings generated by FastEmbedGenerator with stored embeddings.
"""

import duckdb
import numpy as np
import sys
from pathlib import Path

# Add parent directory to path for imports
parent_dir = Path(__file__).parent.parent.absolute()
sys.path.insert(0, str(parent_dir))
sys.path.insert(0, str(parent_dir / 'src'))

from go_doc_go import Config
from go_doc_go.embeddings.fastembed import FastEmbedGenerator


def test_embedding_comparison():
    """Compare newly generated embeddings with stored embeddings."""
    
    print("\n" + "="*80)
    print("EMBEDDING COMPARISON TEST")
    print("="*80 + "\n")
    
    # Initialize FastEmbedGenerator with the correct model
    config = Config()
    embedding_config = config.get('embedding', {})
    model_name = embedding_config.get('model', 'sentence-transformers/all-MiniLM-L6-v2')
    dimensions = embedding_config.get('dimensions', 384)
    
    print(f"1. INITIALIZING FASTEMBED GENERATOR:")
    print(f"   Model: {model_name}")
    print(f"   Dimensions: {dimensions}")
    
    generator = FastEmbedGenerator(
        _config=config,
        model_name=model_name,
        dimensions=dimensions
    )
    
    # Connect to DuckDB and get some sample text
    conn = duckdb.connect(':memory:')
    embeddings_path = 'data-lake/embeddings/**/*.parquet'
    elements_path = 'data-lake/elements/**/*.parquet'
    
    conn.execute(f"CREATE VIEW embeddings AS SELECT * FROM read_parquet('{embeddings_path}')")
    conn.execute(f"CREATE VIEW elements AS SELECT * FROM read_parquet('{elements_path}')")
    
    # Get a sample element with its stored embedding
    print("\n2. GETTING SAMPLE ELEMENT WITH EMBEDDING:")
    
    sample_result = conn.execute("""
        SELECT 
            e.element_id, 
            e.content_preview,
            emb.embedding,
            emb.model
        FROM elements e
        JOIN embeddings emb ON e.element_id = emb.element_id
        WHERE e.content_preview LIKE '%Microsoft%'
        LIMIT 1
    """).fetchone()
    
    if not sample_result:
        # Try another query
        sample_result = conn.execute("""
            SELECT 
                e.element_id, 
                e.content_preview,
                emb.embedding,
                emb.model
            FROM elements e
            JOIN embeddings emb ON e.element_id = emb.element_id
            WHERE LENGTH(e.content_preview) > 50
            LIMIT 1
        """).fetchone()
    
    if sample_result:
        element_id, content_preview, stored_embedding, stored_model = sample_result
        
        print(f"   Element ID: {element_id[:30]}...")
        print(f"   Content: {content_preview[:100]}...")
        print(f"   Stored model: {stored_model}")
        print(f"   Stored embedding dimensions: {len(stored_embedding)}")
        
        # Generate new embedding for the same text
        print("\n3. GENERATING NEW EMBEDDING FOR SAME TEXT:")
        new_embedding = generator.generate(content_preview)
        
        print(f"   Generated embedding dimensions: {len(new_embedding)}")
        
        # Compare embeddings
        print("\n4. COMPARING EMBEDDINGS:")
        
        # Convert to numpy arrays for easier comparison
        stored_arr = np.array(stored_embedding)
        new_arr = np.array(new_embedding)
        
        # Calculate similarity
        dot_product = np.dot(stored_arr, new_arr)
        stored_mag = np.linalg.norm(stored_arr)
        new_mag = np.linalg.norm(new_arr)
        
        if stored_mag > 0 and new_mag > 0:
            cosine_sim = dot_product / (stored_mag * new_mag)
            print(f"   Cosine similarity: {cosine_sim:.6f}")
            
            if cosine_sim > 0.99:
                print("   ✅ Embeddings are nearly identical (>0.99 similarity)")
            elif cosine_sim > 0.9:
                print("   ⚠️ Embeddings are very similar but not identical (>0.9 similarity)")
            elif cosine_sim > 0.7:
                print("   ⚠️ Embeddings are similar but different (>0.7 similarity)")
            else:
                print(f"   ❌ Embeddings are quite different (similarity={cosine_sim:.4f})")
        else:
            print("   ❌ One or both embeddings have zero magnitude")
        
        # Check first few values
        print("\n   First 5 values comparison:")
        print(f"   Stored: {stored_arr[:5]}")
        print(f"   New:    {new_arr[:5]}")
        
        # Check if they're exactly the same
        if np.allclose(stored_arr, new_arr, rtol=1e-5):
            print("\n   ✅ Embeddings are numerically identical (within tolerance)")
        else:
            print("\n   ❌ Embeddings are numerically different")
            
            # Calculate the difference
            diff = np.abs(stored_arr - new_arr)
            print(f"   Max difference: {np.max(diff):.6f}")
            print(f"   Mean difference: {np.mean(diff):.6f}")
            
        # Test with a simple query
        print("\n5. TESTING SEARCH WITH GENERATED EMBEDDING:")
        
        query_text = "Microsoft"
        query_embedding = generator.generate(query_text)
        query_vec_str = '[' + ','.join(map(str, query_embedding)) + ']'
        
        search_query = f"""
        WITH search_results AS (
            SELECT 
                e.element_id,
                e.content_preview,
                (
                    list_dot_product(emb.embedding::DOUBLE[], {query_vec_str}::DOUBLE[]) / 
                    (
                        sqrt(list_dot_product(emb.embedding::DOUBLE[], emb.embedding::DOUBLE[])) * 
                        sqrt(list_dot_product({query_vec_str}::DOUBLE[], {query_vec_str}::DOUBLE[]))
                    )
                ) as similarity
            FROM elements e
            JOIN embeddings emb ON e.element_id = emb.element_id
            WHERE sqrt(list_dot_product(emb.embedding::DOUBLE[], emb.embedding::DOUBLE[])) > 0.0
        )
        SELECT * FROM search_results
        WHERE similarity > 0.3
        ORDER BY similarity DESC
        LIMIT 5
        """
        
        results = conn.execute(search_query).fetchall()
        print(f"   Search for '{query_text}' returned {len(results)} results")
        
        if results:
            for elem_id, preview, sim in results[:3]:
                print(f"     - Similarity {sim:.4f}: {preview[:60]}...")
                
    else:
        print("   ❌ No sample element with embedding found")
    
    conn.close()
    
    print("\n" + "="*80)
    print("TEST COMPLETE")
    print("="*80)


if __name__ == "__main__":
    test_embedding_comparison()