version: '3'
services:
  solr:
    build: .
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  solr_data:
    # This creates a persistent volume for Solr data
