version: '3.8'

services:
  mongodb-test:
    image: mongo:7.0
    container_name: go-doc-go-test-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: go_doc_go_test
    ports:
      - "27017:27017"
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    command: >
      mongod
      --bind_ip_all
      --wiredTigerCacheSizeGB 0.5
      --nojournal
      --quiet
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/go_doc_go_test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - go-doc-go-test-network

networks:
  go-doc-go-test-network:
    name: go-doc-go-test-network
    driver: bridge