version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: go-doc-go-test-postgres
    environment:
      POSTGRES_DB: go_doc_go_test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "15432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    tmpfs:
      # Use tmpfs for better test performance
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=200m
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=128MB
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c max_wal_size=1GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d go_doc_go_test"]
      interval: 2s
      timeout: 1s
      retries: 30
      start_period: 10s
    networks:
      - go-doc-go-test-network

networks:
  go-doc-go-test-network:
    name: go-doc-go-test-network
    driver: bridge